# Generated by Django 2.0.2 on 2018-02-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irontask_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triathlon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heureDepart', models.TimeField()),
                ('codePostal', models.CharField(max_length=5)),
                ('adresse', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTriathlon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('distanceNatation', models.IntegerField(max_length=2)),
                ('distanceCyclisme', models.IntegerField(max_length=4)),
                ('distanceCoursePied', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='triathlon',
            name='typeTriathlon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irontask_back.TypeTriathlon'),
        ),
    ]
