# Generated by Django 2.0.2 on 2018-02-09 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irontask_back', '0002_auto_20180209_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('dateFin', models.DateField()),
                ('duree', models.TimeField()),
                ('nbJoursRappel', models.IntegerField()),
                ('tacheValider', models.BooleanField()),
                ('benevole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irontask_back.Benevole')),
                ('creer_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('triathlon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irontask_back.Triathlon')),
            ],
        ),
    ]
