language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test --top-level-directory

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0.2